logging:
  file:
    name: MarketDataReplayApplication.log
    max-size: 100000GB
  level:
    root: INFO
    org.springframework.web: INFO
springdoc:
  swagger-ui.use-root-path: true
  default-produces-media-type: application/json